/*
 * File: js/app/view/MyWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DiabitiesCamp.view.MyWindow', {
    extend: 'Ext.window.Window',

    height: 465,
    width: 320,
    layout: {
        align: 'stretch',
        padding: 5,
        type: 'vbox'
    },
    title: 'Register New Patient',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    fieldLabel: 'Name'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Age'
                },
                {
                    xtype: 'textareafield',
                    padding: 0,
                    fieldLabel: 'Address'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Mobile Number',
                    spinDownEnabled: false,
                    spinUpEnabled: false
                },
                {
                    xtype: 'radiogroup',
                    flex: 1,
                    width: 293,
                    fieldLabel: 'Male',
                    items: [
                        {
                            xtype: 'radiofield',
                            boxLabel: 'Male'
                        },
                        {
                            xtype: 'radiofield',
                            boxLabel: 'Female'
                        }
                    ]
                },
                {
                    xtype: 'radiogroup',
                    flex: 1,
                    width: 293,
                    fieldLabel: 'Chappal',
                    items: [
                        {
                            xtype: 'radiofield',
                            boxLabel: 'Yes'
                        },
                        {
                            xtype: 'radiofield',
                            boxLabel: 'No'
                        }
                    ]
                },
                {
                    xtype: 'radiogroup',
                    flex: 1,
                    width: 293,
                    fieldLabel: 'Diabities Awareness',
                    items: [
                        {
                            xtype: 'radiofield',
                            boxLabel: 'Yes'
                        },
                        {
                            xtype: 'radiofield',
                            boxLabel: 'No'
                        }
                    ]
                },
                {
                    xtype: 'filefield',
                    flex: 1,
                    fieldLabel: 'Eye Image'
                },
                {
                    xtype: 'filefield',
                    flex: 1,
                    fieldLabel: 'Foot Image'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    flex: 1,
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            text: 'Save Changes'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});