/*
 * File: js/app/view/MyWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DiabitiesCamp.view.Patients', {
    extend: 'gridpanel',
    layout: {
        align: 'stretch',
        padding: 5,
        type: 'vbox'
    },
    title: 'Register New Patient',
	
    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            /*dockedItems: [
                {
                    xtype: 'toolbar',
                    flex: 1,
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            text: 'Save Changes'
                        }
                    ]
                }
            ]*/
        });

        me.callParent(arguments);
    }

});